//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeIngredientShoppingSystem.DataEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Carts = new HashSet<Cart>();
            this.CartRepositories = new HashSet<CartRepository>();
        }
        
        [Display(Name = "Ingredient ID")]
        public int IngredientId { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [Display(Name = "Ingredient Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Recipe ID")]
        [RegularExpression("[0-9]+")]
        public Nullable<int> RecipeId { get; set; }

        [Required]
        [Display(Name = "Manufacturer")]
        public string ManufacturerName { get; set; }

        [Required]
        [Display(Name = "Manufacture Date")]
        public Nullable<System.DateTime> ManufacturerDate { get; set; }

        [Required]
        [Display(Name = "Price")]
        public Nullable<decimal> Price { get; set; }

        [Required]
        [Display(Name = "Expiry Date")]
        public Nullable<System.DateTime> ExpiryDate { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRepository> CartRepositories { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
