//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeIngredientShoppingSystem.DataEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderIngredient()
        {
            this.Shippings = new HashSet<Shipping>();
        }

        [Display(Name = "Order ID")]
        public int OrderId { get; set; }
        [Required]
        [Display(Name = "User ID")]
        [RegularExpression("[0-9]+")]
        public Nullable<int> UserID { get; set; }
        [Required]
        [Display(Name = "Date of Order")]
        public System.DateTime DateOfOrder { get; set; }
        [Required]
        [Display(Name = "Mobile Number")]
        [StringLength(10, ErrorMessage = "The Phone Number should be 10 digits only.", MinimumLength = 10)]
        [RegularExpression(@"^[0-9]{10}$",
         ErrorMessage = "Invalid mobile number: Enter 10 Digits.")]
        public string MobileNumber { get; set; }
        [Required]
        [Display(Name = "Delivery Address")]
        public string DeliveryAddress { get; set; }
        [Required]
        [Display(Name = "Total Bill Amount")]
        public Nullable<decimal> TotalBillAmount { get; set; }
        [Required]
        [Display(Name = "Number of ingredients")]
        [RegularExpression("[0-9]+")]
        public Nullable<int> NoOfIngredients { get; set; }
        [Required]
        [Display(Name = "Grand Total")]
        public Nullable<decimal> GrandTotal { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping> Shippings { get; set; }
    }
}
